repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    - id: flake8
    - id: trailing-whitespace
    - id: requirements-txt-fixer
    - id: pretty-format-json
    - id: no-commit-to-branch
    - id: detect-private-key
    - id: check-json