languange: python
python:
  - "3.6"
env:
  _SUBLIME_TEXT_VERSION ="3"
install:
  - python --version
  - sudo add-apt-repository ppa:webupd8team/sublime-text-3 -y
  - sudo apt-get update
  - sudo apt-get install sublime-text-installer -y
  - subl --version
  - pip install -r requirements.txt
  - python setup.py -develop
  - mkdir -p '~/.config/sublime-text-'$SUBLIME_TEXT_VERSION'/Packages/'
  - ln -s $PWD '~/.config/sublime-text-'$SUBLIME_TEXT_VERSION'/Packages/RESOLVE_COMMENTS'

before_script:
# Generate a screen buffer to collect Sublime Text window
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

# Ensure the scripts self-terminate
 - export SUBLIME_AUTO_KILL=TRUE
script:
  - pylint ./
  - nosetests --nocapture --verbose --stop
notifications:
  email :
    - raphnano@gmail.com
    - km3204@columbia.edu
    - aa2325@columbia.edu
